name: Ubuntu
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

env:
  SCHEME: scheme

jobs:
  build-idris2-with-api:
    runs-on: ubuntu-latest
    env:
      IDRIS2_CG: chez
      IDRIS2_TESTS_CG: chez
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Idris2 commit
        id: get-idris2-commit
        run: echo "idris2-commit=$(git rev-parse @:./Idris2)" >> $GITHUB_ENV
      - name: Cache Idris2 with API
        id: cache-idris2-with-api
        uses: actions/cache@v2
        with:
          path: ~/.idris2/
          key: ${{ env.idris2-commit }}-idris2-with-api
      - name: Get Idris2 Submodule
        if: steps.cache-idris2-with-api.outputs.cache-hit != 'true'
        run: |
          git submodule update --init Idris2
      - name: Install build dependencies
        if: steps.cache-idris2-with-api.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Build Idris2 with API
        if: steps.cache-idris2-with-api.outputs.cache-hit != 'true'
        working-directory: Idris2
        run: |
          make bootstrap && make install
          make clean
          make all && make install
          make install-api

      - name: Checkout idrall repo
        uses: actions/checkout@v2
        with:
          repository: alexhumphreys/idrall
          ref: '65796e03d94fe0063de643461096e69341e88ec0'
          path: idrall
      - name: Build/Install Idrall
        if: steps.cache-idris2-with-api.outputs.cache-hit != 'true'
        working-directory: idrall
        run: |
          make install

      - name: Artifact Idris2 with API
        uses: actions/upload-artifact@v2
        with:
          name: installed-idris2-with-api
          path: ~/.idris2/
          retention-days: 1
  build:
    runs-on: ubuntu-latest
    needs: build-idris2-with-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Idris2 with API Artifact
        uses: actions/download-artifact@v2
        with:
          name: installed-idris2-with-api
          path: ~/.idris2/
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
          chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
      - name: build
        run: |
          make bootstrap
        shell: bash
      # TODO: test
